Repository Team-DevHub/dev-hub-front, pull requests merged in 2024-05, with the labels that each got.

#2 [Feat/#1]: 공통 컴포넌트 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icon/back-icon.svg
  src/assets/icon/comment-icon.svg
  src/assets/icon/filter-arrow.svg
  src/assets/icon/person-icon.svg
  src/assets/image/banner-musseuk.svg
  src/components/common/Banner.tsx
  src/components/common/Header.tsx
  src/components/common/PostItem.tsx
  src/components/common/Tag.tsx
  src/components/homePage/Filter.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/styles/HomeStyle.ts
  src/styles/GlobalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/styled.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#7 [Style/#5]: 홈화면 UI 구현
  src/assets/icon/arrow-left.svg
  src/assets/icon/arrow-right.svg
  src/assets/icon/house-icon.svg
  src/assets/icon/pencil-icon.svg
  src/assets/icon/search-icon.svg
  src/assets/image/lv5.svg
  src/components/common/Banner.tsx
  src/components/common/Button.tsx
  src/components/common/Category.tsx
  src/components/common/Header.tsx
  src/components/common/Pagination.tsx
  src/components/common/Tag.tsx
  src/components/homePage/Filter.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/PostList.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SearchInput.tsx
  src/components/homePage/SideBar.tsx
  src/components/homePage/Top5.tsx
  src/components/homePage/TopUser.tsx
  src/data/categories.ts
  src/data/postDummy.ts
  src/pages/HomePage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/styled.d.ts
  yarn.lock
Labels: style

#10 [Feat/#8]: pagination 구현
  src/assets/icon/icons.ts
  src/components/common/FormInput/Checkbox.tsx
  src/components/common/FormInput/FormButton.tsx
  src/components/common/FormInput/FormInput.tsx
  src/components/common/Pagination.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/PostList.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SearchInput.tsx
  src/components/homePage/SideBar.tsx
  src/data/postDummy.ts
  src/pages/HomePage.tsx
Labels: feat

#11 [Style, Feat/#9]: 로그인, 회원가입, 비밀번호 페이지 퍼블리싱 및 로그인 라우터 분리
  src/App.tsx
  src/assets/icon/ic-join.svg
  src/assets/icon/icons.ts
  src/assets/image/account-musseuk.svg
  src/components/account/AccountLayout.tsx
  src/components/account/FindPasswordForm.tsx
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/common/FormInput/Checkbox.tsx
  src/components/common/FormInput/FormButton.tsx
  src/components/common/FormInput/FormInput.tsx
  src/constants/path.ts
  src/constants/storage.ts
  src/pages/account/AccountPage.tsx
  src/provider/LoginProvider.tsx
  src/styles/GlobalStyle.tsx
Labels: feat, style

#15 [Feat/#14]: 팝업 구현
  package-lock.json
  package.json
  src/assets/icon/icons.ts
  src/assets/icon/level-icon.svg
  src/assets/icon/signout-icon.svg
  src/assets/icon/warning-icon.svg
  src/assets/image/delete-musseuk.svg
  src/assets/image/warning-musseuk.svg
  src/assets/level/Lv.1.svg
  src/assets/level/Lv.2.svg
  src/assets/level/Lv.3.svg
  src/assets/level/Lv.4.svg
  src/assets/level/Lv.5.svg
  src/components/common/Button.tsx
  src/components/common/FormInput/FormButton.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/MyLevel.tsx
  src/components/popup/DeleteAccountPopUp.tsx
  src/components/popup/LevelPopUp.tsx
  src/components/popup/NonMemberPopUp.tsx
  src/components/popup/PopUpLayout.tsx
  src/components/popup/item/ActivityBox.tsx
  src/components/popup/item/LevelItem.tsx
  src/constants/level.ts
  src/data/levelData.ts
  src/pages/components/ComponentPage.tsx
  src/styles/GlobalStyle.tsx
  src/styles/variants.ts
  src/utils/useClickOutside.ts
  yarn.lock
Labels: feat

#20 [Feat/#19] 게시글 작성 페이지 구현
  package-lock.json
  package.json
  src/components/common/Category.tsx
  src/components/modal/Link.tsx
  src/components/modal/PostDetail.tsx
  src/components/posting/ContentInput.tsx
  src/components/posting/LinkInput.tsx
  src/components/posting/TitleInput.tsx
  src/pages/HomePage.tsx
  src/pages/PostingPage.tsx
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: feat

#22 [API/#21]: 회원 API 연동, Zustand 적용
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/api/instance.ts
  src/api/userAPI.ts
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/common/CommentInputBar/CommmentInpuBart.tsx
  src/components/common/FormInput/FormInput.tsx
  src/components/common/Tag.tsx
  src/components/homePage/Filter.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/SearchInput.tsx
  src/components/homePage/SideBar.tsx
  src/components/modal/PostModal.tsx
  src/components/myPage/MyInfo.tsx
  src/constants/storage.ts
  src/provider/LoginProvider.tsx
  src/store/store.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/api/request.d.ts
  src/types/api/response.d.ts
  yarn.lock
Labels: API, style
