Repository Team-DevHub/dev-hub-front, pull requests merged in 2024-06, with the labels that each got.

#24 [API/#23]: 회원 API 연동
  .eslintrc.cjs
  src/api/instance.ts
  src/api/userAPI.ts
  src/components/account/FindPasswordForm.tsx
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/Top5.tsx
  src/components/myPage/MyActivity.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/MyLevel.tsx
  src/components/popup/DeleteAccountPopUp.tsx
  src/constants/level.ts
  src/hooks/useLevel.tsx
  src/pages/HomePage.tsx
  src/store/store.ts
  src/types/api/request.d.ts
  src/types/api/response.d.ts
Labels: API

#27 [Style/#26]: 404 페이지, 로고 추가
  index.html
  package-lock.json
  public/logo.png
  public/vite.svg
  src/App.tsx
  src/assets/icon/arrow-home.svg
  src/assets/icon/back-icon.svg
  src/assets/icon/comment-send-icon.svg
  src/assets/icon/delete-account-icon.svg
  src/assets/icon/icons.ts
  src/assets/icon/logout-icon.svg
  src/assets/icon/share.svg
  src/assets/icon/warning.svg
  src/assets/image/musseuk_404.svg
  src/assets/logo/logo-key.svg
  src/assets/logo/logo-no-bg.svg
  src/assets/logo/logo-white.svg
  src/components/common/Banner.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/homePage/NonMemberProfile.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SideBar.tsx
  src/components/myPage/MyInfo.tsx
  src/components/popup/item/ActivityBox.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PostingPage.tsx
  src/styles/theme.ts
  vite.config.ts
  yarn.lock
Labels: style

#29 [Feat/#28]: 닉네임 중복 API 연동 & 디자인 수정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api/userAPI.ts
  src/assets/icon/arrow-back.svg
  src/assets/icon/arrow-go.svg
  src/assets/icon/github.svg
  src/assets/icon/icons.ts
  src/assets/icon/notion.svg
  src/assets/logo/logo-gray.svg
  src/assets/logo/logo-key.svg
  src/components/account/FindPasswordForm.tsx
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/common/Footer/FeedBackInput.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/FormInput/FormButton.tsx
  src/components/common/FormInput/FormInput.tsx
  src/components/common/Header.tsx
  src/components/homePage/Filter.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SearchInput.tsx
  src/components/homePage/Top5.tsx
  src/components/layouts/AccountLayout.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/PopUpLayout.tsx
  src/components/modal/CommmentInpuBar.tsx
  src/components/modal/PostModal.tsx
  src/components/myPage/MyActivity.tsx
  src/components/myPage/MyInfo.tsx
  src/components/popup/DeleteAccountPopUp.tsx
  src/components/popup/LevelPopUp.tsx
  src/components/popup/NonMemberPopUp.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useLevel.ts
  src/hooks/useProfile.ts
  src/pages/HomePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/account/AccountPage.tsx
  src/store/store.ts
  src/styles/GlobalStyle.tsx
  src/styles/component.ts
  src/styles/theme.ts
  src/types/api/response.d.ts
  src/utils/regex.ts
  yarn.lock
Labels: feat

#31 [Feat/#30]: 배너, 팝업 등 유저 데이터 연결, top5 아이콘 변경 등
  src/App.tsx
  src/api/instance.ts
  src/api/userAPI.ts
  src/assets/top5/top1.svg
  src/assets/top5/top2.svg
  src/assets/top5/top3.svg
  src/assets/top5/top4.svg
  src/assets/top5/top5.svg
  src/components/account/JoinForm.tsx
  src/components/common/Banner.tsx
  src/components/homePage/TopUser.tsx
  src/components/layouts/ScrollToTop.tsx
  src/components/myPage/MyPostLIst.tsx
  src/components/popup/LevelPopUp.tsx
  src/components/popup/item/ActivityBox.tsx
  src/components/popup/item/LevelItem.tsx
  src/constants/message.ts
  src/constants/top5.ts
  src/data/levelData.ts
  src/pages/MyPage.tsx
Labels: feat

#32 [Api/#25]: 게시글 API 연동
  netlify.toml
  package-lock.json
  src/api/postAPI.ts
  src/assets/icon/icons.ts
  src/assets/icon/question-icon.svg
  src/components/common/Button.tsx
  src/components/common/Category.tsx
  src/components/common/Pagination.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/PostList.tsx
  src/components/homePage/SearchInput.tsx
  src/components/modal/CommentItem.tsx
  src/components/modal/CommentList.tsx
  src/components/modal/CommmentInpuBar.tsx
  src/components/modal/Link.tsx
  src/components/modal/PostDetail.tsx
  src/components/modal/PostModal.tsx
  src/components/myPage/MyPostEmpty.tsx
  src/components/myPage/MyPostLIst.tsx
  src/components/posting/ContentInput.tsx
  src/components/posting/LinkInput.tsx
  src/components/posting/TitleInput.tsx
  src/components/posts/PostEmpty.tsx
  src/data/categories.ts
  src/hooks/useModal.ts
  src/hooks/usePosts.ts
  src/pages/HomePage.tsx
  src/pages/PostingPage.tsx
  src/store/store.ts
  src/types/api/request.d.ts
  src/types/api/response.d.ts
  src/utils/format.ts
  src/utils/getCategoryName.ts
  yarn.lock
Labels: fix, API, feat

#38 [Fix/#37] : 디자인, search input, API 수정
  public/assets/icon/x-icon.svg
  src/components/homePage/Filter.tsx
  src/components/homePage/PostList.tsx
  src/components/homePage/SearchInput.tsx
  src/components/modal/CommentItem.tsx
  src/components/modal/CommentList.tsx
  src/components/modal/PostDetail.tsx
  src/components/modal/PostModal.tsx
  src/components/myPage/MyPostEmpty.tsx
  src/components/myPage/MyPostLIst.tsx
  src/constants/icons.ts
  src/data/commentDummy.ts
  src/data/myPostDummy.ts
  src/data/postDummy.ts
  src/hooks/usePosts.ts
Labels: fix

#40 [Feat/#36]: 배너 슬라이드 구현, 디자인 변경사항 반영
  package-lock.json
  package.json
  public/assets/icon/check.svg
  public/assets/icon/logout-icon.svg
  public/assets/image/max-musseuk.svg
  public/assets/image/people.svg
  src/components/account/FindPasswordForm.tsx
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/common/Banner/Banner.tsx
  src/components/common/Banner/BannerSlider.tsx
  src/components/common/Banner/BannerWithTitle.tsx
  src/components/common/Banner/GuideBanner.tsx
  src/components/common/Footer/FeedBackInput.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/FormInput/Checkbox.tsx
  src/components/common/Header.tsx
  src/components/common/Pagination.tsx
  src/components/homePage/NonMemberProfile.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SearchInput.tsx
  src/components/homePage/SideBar.tsx
  src/components/layouts/AccountLayout.tsx
  src/components/modal/CommentItem.tsx
  src/components/modal/CommmentInpuBar.tsx
  src/components/modal/Link.tsx
  src/components/modal/PostDetail.tsx
  src/components/myPage/MyActivity.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/MyLevel.tsx
  src/components/myPage/MyPostEmpty.tsx
  src/components/myPage/MyPostLIst.tsx
  src/components/popup/DeleteAccountPopUp.tsx
  src/components/popup/LevelPopUp.tsx
  src/components/popup/NonMemberPopUp.tsx
  src/components/popup/item/ActivityBox.tsx
  src/components/posting/LinkInput.tsx
  src/components/posts/PostEmpty.tsx
  src/constants/assets.ts
  src/data/levelData.ts
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PostingPage.tsx
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: feat

#41 [Fix/#39] 글 작성 페이지 에디터 수정
  src/components/posting/ContentInput.tsx
Labels: fix

#43 [Fix/#42] : 닉네임 글자수 제한 및 디자인 수정
  public/assets/icon/arrow-left.svg
  public/assets/icon/arrow-right.svg
  src/components/account/JoinForm.tsx
  src/components/common/Banner/Banner.tsx
  src/components/common/Banner/BannerWithTitle.tsx
  src/components/common/Pagination.tsx
  src/components/modal/Link.tsx
  src/components/modal/PostDetail.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/MyPostLIst.tsx
  yarn.lock
Labels: fix

#44 [Style/#42] 링크 디자인 수정
  src/components/common/Pagination.tsx
  src/components/modal/Link.tsx
Labels: fix, style

#47 [Style/#46] 페이지네이션 아이콘 수정
  public/assets/icon/arrow-left.svg
  public/assets/icon/arrow-right.svg
  src/components/common/Pagination.tsx
Labels: style

#49 [Feat/#48]: react-query 적용 (회원 API)
  package-lock.json
  package.json
  src/App.tsx
  src/api/queryClient.ts
  src/api/requests/postAPI.ts
  src/api/requests/userAPI.ts
  src/components/account/FindPasswordForm.tsx
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/common/Banner/Banner.tsx
  src/components/homePage/PostItem.tsx
  src/components/homePage/PostList.tsx
  src/components/homePage/Profile.tsx
  src/components/homePage/SideBar.tsx
  src/components/homePage/Top5.tsx
  src/components/layouts/ScrollToTop.tsx
  src/components/modal/CommentItem.tsx
  src/components/modal/CommmentInpuBar.tsx
  src/components/myPage/MyActivity.tsx
  src/components/myPage/MyInfo.tsx
  src/components/myPage/MyLevel.tsx
  src/components/myPage/MyPostLIst.tsx
  src/components/popup/DeleteAccountPopUp.tsx
  src/components/popup/LevelPopUp.tsx
  src/components/popup/item/ActivityBox.tsx
  src/hooks/useAuth.ts
  src/hooks/useLevel.ts
  src/hooks/useModal.ts
  src/hooks/usePassword.ts
  src/hooks/usePosts.ts
  src/hooks/useProfile.ts
  src/hooks/useUserInfo.ts
  src/hooks/useVerification.ts
  src/models/common.model.ts
  src/models/post.model.ts
  src/models/user.model.ts
  src/pages/HomePage.tsx
  src/pages/PostingPage.tsx
  src/store/store.ts
  src/types/api/request.d.ts
  yarn.lock
Labels: feat

#53 [Style/#52]: 중복확인 메시지 위치 수정
  src/components/account/JoinForm.tsx
  src/components/common/FormInput/FormInput.tsx
  src/components/layouts/AccountLayout.tsx
Labels: style

#54 [Feat/#50]: 카테고리 수정, 토큰 만료 처리
  src/api/instance.ts
  src/api/requests/postAPI.ts
  src/api/requests/userAPI.ts
  src/data/categories.ts
  src/pages/NotFoundPage.tsx
Labels: feat

#56 [Feat/#55] react-query 적용 (post API)
  src/api/instance.ts
  src/components/modal/CommentItem.tsx
  src/hooks/useComment.ts
  src/hooks/useMyPosts.ts
  src/hooks/usePosts.ts
  yarn.lock
Labels: feat

#58 [Fix/#57]: 삭제 버튼 오류 수정
  src/components/popup/ConfirmPopUp.tsx
  src/components/popup/PopUps.tsx
  src/store/popUpStore.ts
Labels: fix

#60 [Fix/#59]: 회원탈퇴 팝업 수정
  src/components/popup/item/ActivityBox.tsx
Labels: fix

#61 [Fix/#59]: refetch 적용
  src/components/popup/PopUps.tsx
  src/hooks/useUserInfo.ts
Labels: fix

#64 [Feat/#63]: 깃허브 소셜 로그인 구현
  public/assets/icon/github-button.svg
  public/assets/icon/google.svg
  src/api/instance.ts
  src/api/requests/authAPI.ts
  src/components/account/LoginForm.tsx
  src/components/account/OAuthButtons.tsx
  src/components/layouts/AccountLayout.tsx
  src/components/myPage/MyInfo.tsx
  src/constants/assets.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
Labels: feat
