Repository Team-DevHub/dev-hub-front, pull requests merged in 2024-07, with the labels that each got.

#66 [Feat/#65] : 게시글 수정 API 연동
  public/assets/icon/edit-icon.svg
  src/App.tsx
  src/api/instance.ts
  src/api/requests/postAPI.ts
  src/components/common/Category.tsx
  src/components/modal/PostDetail.tsx
  src/components/modal/PostForm.tsx
  src/components/modal/PostModal.tsx
  src/components/posting/TitleInput.tsx
  src/constants/assets.ts
  src/hooks/useEdit.ts
  src/pages/EditPostPage.tsx
  src/pages/PostingPage.tsx
Labels: API, feat

#69 [API/#68]: 구글 로그인 API 연동
  src/api/requests/authAPI.ts
  src/components/account/LoginForm.tsx
  src/components/account/OAuthButtons.tsx
  src/constants/storage.ts
  src/hooks/useAuth.ts
  src/models/auth.model.ts
Labels: API

#73 [Style/#72]: 게시글 수정 팝업 타이틀 수정
  src/components/modal/PostDetail.tsx
  src/constants/alertType.ts
  src/pages/EditPostPage.tsx
  src/store/popUpStore.ts
Labels: style

#75 [Fix/#74]: 로그인 정보 저장 -> 자동 로그인
  src/api/instance.ts
  src/components/account/JoinForm.tsx
  src/components/account/LoginForm.tsx
  src/hooks/useAuth.ts
Labels: fix

#79 [API]: 스크랩 관련 API 재연동
  src/api/instance.ts
  src/api/requests/postAPI.ts
  src/components/modal/PostDetail.tsx
  src/hooks/useMyPosts.ts
  src/models/post.model.ts
Labels: fix, API

#81 [Fix/#80]: 로그인 에러 핸들링 수정
  src/api/requests/userAPI.ts
Labels: fix

#84 [Fix/#83]: 일부 수정사항
  public/assets/logo/logo-gray.svg
  public/assets/logo/logo-key.svg
  public/assets/logo/logo-no-bg.svg
  public/assets/logo/logo-white.svg
  public/logo.png
  src/components/account/OAuthButtons.tsx
Labels: fix
